package interfaces;

import persistencia.BD;
import controle.*;

public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        BD.initiateDatabase();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JMenuBar();
        MostrarMenu = new javax.swing.JMenu();
        HomemMenuItem = new javax.swing.JMenuItem();
        MulherMenuItem = new javax.swing.JMenuItem();
        TagMenuItem = new javax.swing.JMenuItem();
        EditarMenu = new javax.swing.JMenu();
        SoloEditarMenu = new javax.swing.JMenu();
        SoloAlterarMenuItem = new javax.swing.JMenuItem();
        SoloInserirRemoverMenuItem = new javax.swing.JMenuItem();
        TagTeamEditarMenu = new javax.swing.JMenu();
        TagTeamAlterarMenuItem = new javax.swing.JMenuItem();
        TagTeamInserirRemoverMenuItem = new javax.swing.JMenuItem();
        MatchMenu = new javax.swing.JMenu();
        SoloMatch = new javax.swing.JMenuItem();
        TagTeamMatch = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Rank");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                terminarSistema(evt);
            }
        });

        MostrarMenu.setText("Mostrar");

        HomemMenuItem.setText("Homem");
        HomemMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomemMenuItemActionPerformed(evt);
            }
        });
        MostrarMenu.add(HomemMenuItem);

        MulherMenuItem.setText("Mulher");
        MostrarMenu.add(MulherMenuItem);

        TagMenuItem.setText("Tag Team");
        MostrarMenu.add(TagMenuItem);

        Menu.add(MostrarMenu);

        EditarMenu.setText("Edit");

        SoloEditarMenu.setText("Solo");

        SoloAlterarMenuItem.setText("Alterar");
        SoloAlterarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoloAlterarMenuItemActionPerformed(evt);
            }
        });
        SoloEditarMenu.add(SoloAlterarMenuItem);

        SoloInserirRemoverMenuItem.setText("Inserir/Remover");
        SoloInserirRemoverMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoloInserirRemoverMenuItemActionPerformed(evt);
            }
        });
        SoloEditarMenu.add(SoloInserirRemoverMenuItem);

        EditarMenu.add(SoloEditarMenu);

        TagTeamEditarMenu.setText("Tag Team");

        TagTeamAlterarMenuItem.setText("Alterar");
        TagTeamEditarMenu.add(TagTeamAlterarMenuItem);

        TagTeamInserirRemoverMenuItem.setText("Inserir/Remover");
        TagTeamEditarMenu.add(TagTeamInserirRemoverMenuItem);

        EditarMenu.add(TagTeamEditarMenu);

        Menu.add(EditarMenu);

        MatchMenu.setText("Match");
        MatchMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MatchMenu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        SoloMatch.setText("Solo");
        SoloMatch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SoloMatch.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        SoloMatch.setIconTextGap(0);
        SoloMatch.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SoloMatch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SoloMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoloMatchActionPerformed(evt);
            }
        });
        MatchMenu.add(SoloMatch);

        TagTeamMatch.setText("Tag Team");
        MatchMenu.add(TagTeamMatch);

        Menu.add(MatchMenu);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SoloMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoloMatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoloMatchActionPerformed

    private void HomemMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomemMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomemMenuItemActionPerformed

    private void SoloAlterarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoloAlterarMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoloAlterarMenuItemActionPerformed

    private void SoloInserirRemoverMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoloInserirRemoverMenuItemActionPerformed
        new ControladorCadastroSolo();
    }//GEN-LAST:event_SoloInserirRemoverMenuItemActionPerformed

    private void terminarSistema(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_terminarSistema
        BD.fechaConexão();
        System.exit(1);
    }//GEN-LAST:event_terminarSistema

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EditarMenu;
    private javax.swing.JMenuItem HomemMenuItem;
    private javax.swing.JMenu MatchMenu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MostrarMenu;
    private javax.swing.JMenuItem MulherMenuItem;
    private javax.swing.JMenuItem SoloAlterarMenuItem;
    private javax.swing.JMenu SoloEditarMenu;
    private javax.swing.JMenuItem SoloInserirRemoverMenuItem;
    private javax.swing.JMenuItem SoloMatch;
    private javax.swing.JMenuItem TagMenuItem;
    private javax.swing.JMenuItem TagTeamAlterarMenuItem;
    private javax.swing.JMenu TagTeamEditarMenu;
    private javax.swing.JMenuItem TagTeamInserirRemoverMenuItem;
    private javax.swing.JMenuItem TagTeamMatch;
    // End of variables declaration//GEN-END:variables
}
